### ISSUE TITLE
Can't pickle UUID

### ISSUE THREAD

**Issue by sontek** [jsonpickle/jsonpickle#130]
```
>>> import jsonpickle
>>> import uuid
>>> data = uuid.uuid4()
>>> encoded = jsonpickle.encode(data)
>>> decoded = jsonpickle.decode(encoded)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sontek/venvs/smlib.cache/local/lib/python2.7/site-packages/jsonpickle/__init__.py", line 148, in decode
    return unpickler.decode(string, backend=backend, keys=keys)
  File "/home/sontek/venvs/smlib.cache/local/lib/python2.7/site-packages/jsonpickle/unpickler.py", line 26, in decode
    return context.restore(backend.decode(string), reset=reset)
  File "/home/sontek/venvs/smlib.cache/local/lib/python2.7/site-packages/jsonpickle/unpickler.py", line 119, in restore
    value = self._restore(obj)
  File "/home/sontek/venvs/smlib.cache/local/lib/python2.7/site-packages/jsonpickle/unpickler.py", line 159, in _restore
    return restore(obj)
  File "/home/sontek/venvs/smlib.cache/local/lib/python2.7/site-packages/jsonpickle/unpickler.py", line 243, in _restore_object
    return self._restore_object_instance(obj, cls)
  File "/home/sontek/venvs/smlib.cache/local/lib/python2.7/site-packages/jsonpickle/unpickler.py", line 308, in _restore_object_instance
    return self._restore_object_instance_variables(obj, instance)
  File "/home/sontek/venvs/smlib.cache/local/lib/python2.7/site-packages/jsonpickle/unpickler.py", line 337, in _restore_object_instance_variables
    self._restore_from_dict(obj, instance)
  File "/home/sontek/venvs/smlib.cache/local/lib/python2.7/site-packages/jsonpickle/unpickler.py", line 326, in _restore_from_dict
    setattr(instance, k, value)
  File "/usr/lib/python2.7/uuid.py", line 195, in __setattr__
    raise TypeError('UUID objects are immutable')
TypeError: UUID objects are immutable

```

I can do it manually though:

```
>>> import json
>>> from uuid import UUID
>>> UUID(int=json.loads(encoded)['int'])
UUID('c88e579d-c9dc-43a9-9991-9b4dc4aeb6f4')
```

**Comment by martin-langhoff** [comment]
I just hit this too. Good old pickle module can handle UUID objects alright:
```
u = uuid.UUID()
p = pickle.dumps(u)
ux = pickle.loads(p)
ux is now UUID('819e4aa4-978d-462a-923c-dd1cb18a05f3')
```

**Comment by davvid** [comment]
Thanks for the heads-up.  It should work now and forevermore (I added a test case)
