### ISSUE TITLE
Unpickling collection.deque fails with ValueError on Python 3.6 

### ISSUE THREAD

**Issue by ambv** [jsonpickle/jsonpickle#163]
```
======================================================================
ERROR: Make sure we can handle collections.deque
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/tmp/jsonpickle/jsonpickle/tests/object_test.py", line 315, in test_deque_roundtrip
    new_deque = jsonpickle.decode(encoded)
  File "/private/tmp/jsonpickle/jsonpickle/jsonpickle/__init__.py", line 152, in decode
    return unpickler.decode(string, backend=backend, keys=keys)
  File "/private/tmp/jsonpickle/jsonpickle/jsonpickle/unpickler.py", line 27, in decode
    return context.restore(backend.decode(string), reset=reset)
  File "/private/tmp/jsonpickle/jsonpickle/jsonpickle/unpickler.py", line 120, in restore
    value = self._restore(obj)
  File "/private/tmp/jsonpickle/jsonpickle/jsonpickle/unpickler.py", line 162, in _restore
    return restore(obj)
  File "/private/tmp/jsonpickle/jsonpickle/jsonpickle/unpickler.py", line 243, in _restore_object
    instance = handler(self).restore(obj)
  File "/private/tmp/jsonpickle/jsonpickle/jsonpickle/handlers.py", line 218, in restore
    factory, args = [restore(i, reset=False) for i in data['__reduce__']]
ValueError: too many values to unpack (expected 2)

----------------------------------------------------------------------
```

**Comment by seperman** [comment]
I get the same error running that test on python 3.6.

**Comment by marscher** [comment]
strangely reduce returns a 4-element tuple on python 3.6, eg:
[<class 'collections.deque'>, ((), 60), None, <list_iterator object at 0x7fad705f8f60>]

**Comment by marscher** [comment]
https://docs.python.org/3/library/pickle.html#object.__reduce__ states, that the reduce result tuple can contain two till five values. So I think the tuple unpacking jsonpickle does not treat that right, because it always tries to split in two values.

**Comment by ambv** [comment]
✨ 🍰 ✨

**Comment by marcintustin** [comment]
This is broken because SimpleReduceHandler existed to handle the python 2 reduce protocol. In fact, jsonpickle's default handlers already handle the full protocol. I'm going to open a PR to remove this class.
