### ISSUE TITLE
List Index out of bound when decoding some objects

### ISSUE THREAD

**Issue by JudgeJimmie** [jsonpickle/jsonpickle#182]
Hey David,

I am seeing an issue where when decoding objects that require tagIDs I can sometimes hit an index out of bounds exception. Traceback is below. 

I have found that if I replace the get method in the _IDProxy class to return None this problem goes away, and this seems like the intended behavior as well. Since this is a proxy object it seems that it shouldn't be expected for this _IDProxy to return a valid value. Currently in _restore_id we are trying to access this value, catching the exception, and then creating a proxy that is set up to commit the same error. From code inspection it looks to me that _IDProxy should match _Proxy implementation like so:

class _IDProxy(_Proxy):
    def __init__(self, objs, index):
        self._index = index
        self._objs = objs

    def get(self):
        try:
            return self._objs[self._index]
        except IndexError:
            return None

Where None is returned if the objs list is not fully populated.

    object = jsonpickle.decode(json)
  File "/usr/local/lib/python3.6/site-packages/jsonpickle/__init__.py", line 149, in decode
    return unpickler.decode(string, backend=backend, keys=keys)
  File "/usr/local/lib/python3.6/site-packages/jsonpickle/unpickler.py", line 26, in decode
    return context.restore(backend.decode(string), reset=reset)
  File "/usr/local/lib/python3.6/site-packages/jsonpickle/unpickler.py", line 129, in restore
    self._swap_proxies()
  File "/usr/local/lib/python3.6/site-packages/jsonpickle/unpickler.py", line 135, in _swap_proxies
    method(obj, attr, proxy)
  File "/usr/local/lib/python3.6/site-packages/jsonpickle/unpickler.py", line 83, in _obj_setattr
    setattr(obj, attr, proxy.get())
  File "/usr/local/lib/python3.6/site-packages/jsonpickle/unpickler.py", line 79, in get
    return self._objs[self._index]
IndexError: list index out of range

Love this tool by the way! Thanks for all of the effort you've put into it!

**Comment by JudgeJimmie** [comment]
I believe this may be related to how you handle FileHandlers and python3, but not sure how yet.

**Comment by davvid** [comment]
If you can help put together a minimal reproducible test case that'll help dig into it a bit.  That traceback might be showing a limitation in the current approach, as returning None there might make it work, but it's losing data there.  We should really be indexing the objects by some other means rather than the index.. and there's probably a mismatch between encoder/decoder that the None is papering over.

I'm curious to see what type of object can do this.  A unit test (see the `tests` directory, and `make test`) would go a long way.

The current proxy and referencing scheme has some limitations with read-only objects, which would be nice to eliminate.  Objects with issues are namely tuples, file objects, database handles, C extensions, and other things of that ilk.  We implement a pickle protocol that can be used to help proxy away these types of objects.

To make things work with the current implementation, the `__getstate__`  and `__setstate__` protocol can be used on a class to proxy these types of objects, and from inside those methods use new instances of the Pickler and Unpickler classes to pickle specific object subgraphs that don't have these issues.

**Comment by JudgeJimmie** [comment]
Thanks David. I definitely have plenty of read-only objects here, including Obj-C bridges and file objects. It may be best for me to implement the get state and set state method in each of my objects. In the meantime, if I can recreate this issue using a simple unit test I will send it your way to have a look.

**Comment by sepstein12** [comment]
Hi David.  I have encountered the same issue.  In context.restore    value = self._restore(obj)    succeeds, i.e. the Python object gets created.  Then _swap_proxies() loops through 3 proxies.  method(obj, attr, proxy)   calls  _IDProxy.get    In the third time through the loop there are the following values in self in _IDProxy.get:
- self._index   is 20
- self.obj        is a list that has 20 elements, 0 through 19.

So this statement;    return self._objs[self._index]       begets this:  IndexError: list index out of range

    def _swap_proxies(self):
        """Replace proxies with their corresponding instances"""
        for (obj, attr, proxy, method) in self._proxies:
            method(obj, attr, proxy)
        self._proxies = []
calls:
def _obj_setvalue(obj, idx, proxy):
    obj[idx] = proxy.get()

calls:
    def get(self):
        return self._objs[self._index]

I've tried to create test data that I can send to reproduce the issue.  When I capture the data (via a print statement) that results in the failure and then copy that to a short program that just calls    jsonpickle.decode   I end up with other errors that don't happen in "the real program" (e.g. errors with control characters \n)  (and e.g. ValueError: Expecting , delimiter: line 1 column 3347 (char 3346) - an error that does not occur when I just pass the string to jsonpickle.decode in the real software).   The control characters and the funky construct that causes the "Expecting ," are in the data passed to jsonpickle.decode in the real program - and they get decoded fine there, but not in the simple program that only calls jsonpickle.decode.  

So I don't have test data available that reproduces the error in a test case (even though I have captured the data).

**Comment by mspacek** [comment]
I know this is an old issue, but I've recently run up against it as well, in the latest pypi packaged version of jsonpickle 1.2, with the latest simplejson and numpy, in both Python 2.7.15 and Python 3.6.8. I'm using the numpy extension. The simplejson encoder options don't seem to matter:

```python
import jsonpickle
jsonpickle.set_preferred_backend('simplejson') # make default explicit
jsonpickle.set_encoder_options('simplejson',
                               indent=1, separators=(',', ':'), sort_keys=True) # more readable
import jsonpickle.ext.numpy as jsonpickle_numpy
jsonpickle_numpy.register_handlers()
```

I have a large complex object that I can reliably generate to trigger this error. Unfortunately, I'm not sure what it is about this object that makes it special, and the code that generates it is itself complex. The one particular object being decoded that triggers this error is a numpy float64 scalar that is referenced to another `id()`-identical numpy scalar. I have two of them that are generated with something like:

```python
s, = abs(sls.p) # sls.p is a numpy array of length 1
sx, sy = s, s
sort.sls.sx = sx
sort.sls.sy = sy
```
where `sort` is my top-level object and `sls` is a child object. In the json output, `sy` references (presumably) `sx`, but the `py/id` is out of range of jsonpickle's proxies list.

Here's the traceback, with some manual debugging:
```
Running spyke in Python 2.7
PyOpenGL 3.1.0
simplejson 3.16.0
matplotlib 2.2.4
PyQt4 4.12.1
scipy 1.2.2
pywt 1.0.3
IPython 5.8.0
mdp 3.5
cython 0.29.13
Qt4 4.8.7
Python 2.7.15+
jsonpickle 1.2
numpy 1.16.5
sklearn 0.20.4
Opening file '/home/mspacek/Desktop/json_test/blab1b/revert2broken/Ntsr1Cre_2019_0004_s03.track.json'
Opening sort file 'Ntsr1Cre_2019_0004_s03.track.json'
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
/home/mspacek/dev/spyke/spyke/main.py in OpenRecentFile(self)
   2573         if action:
   2574             fullfname = qvar2str(action.data())
-> 2575             self.OpenFile(fullfname)
   2576 
   2577     def updateRecentFiles(self, fullfname=None):

/home/mspacek/dev/spyke/spyke/main.py in OpenFile(self, fname)
   2621         elif ext in ['.sort', '.json']:
   2622             self.sortpath = head
-> 2623             self.OpenSortFile(tail)
   2624         else:
   2625             critical = QtGui.QMessageBox.critical

/home/mspacek/dev/spyke/spyke/main.py in OpenSortFile(self, fname)
   3408         elif ext == '.json':
   3409             with open(os.path.join(self.sortpath, fname), 'r') as f:
-> 3410                 sort = jsonpickle.decode(f.read(), keys=True)
   3411                 nbytes = f.tell()
   3412         print('Done opening sort file, took %.3f sec' % (time.time()-t0))

/usr/local/lib/python2.7/dist-packages/jsonpickle/unpickler.pyc in decode(string, backend, context, keys, reset, safe, classes)
     39     context = context or Unpickler(keys=keys, backend=backend, safe=safe)
     40     data = backend.decode(string)
---> 41     return context.restore(data, reset=reset, classes=classes)
     42 
     43 

/usr/local/lib/python2.7/dist-packages/jsonpickle/unpickler.pyc in restore(self, obj, reset, classes)
    150         value = self._restore(obj)
    151         if reset:
--> 152             self._swap_proxies()
    153         return value
    154 

/usr/local/lib/python2.7/dist-packages/jsonpickle/unpickler.pyc in _swap_proxies(self)
    168         """Replace proxies with their corresponding instances"""
    169         for (obj, attr, proxy, method) in self._proxies:
--> 170             method(obj, attr, proxy)
    171         self._proxies = []
    172 

/usr/local/lib/python2.7/dist-packages/jsonpickle/unpickler.pyc in _obj_setattr(obj, attr, proxy)
     99 
    100 def _obj_setattr(obj, attr, proxy):
--> 101     setattr(obj, attr, proxy.get())
    102 
    103 

/usr/local/lib/python2.7/dist-packages/jsonpickle/unpickler.pyc in get(self)
     95 
     96     def get(self):
---> 97         return self._objs[self._index]
     98 
     99 

IndexError: list index out of range
> /usr/local/lib/python2.7/dist-packages/jsonpickle/unpickler.py(97)get()
     95 
     96     def get(self):
---> 97         return self._objs[self._index]
     98 
     99 

ipdb> len(self._objs)
1078
ipdb> self._index
1098
ipdb> u
> /usr/local/lib/python2.7/dist-packages/jsonpickle/unpickler.py(101)_obj_setattr()
     99 
    100 def _obj_setattr(obj, attr, proxy):
--> 101     setattr(obj, attr, proxy.get())
    102 
    103 

ipdb> obj
<spyke.extract.SpatialLeastSquares object at 0x7fa5ae504190>
ipdb> dir(obj)
['A', '__class__', '__delattr__', '__dict__', '__doc__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'calc_s', 'calc_sxsy', 'calc_sy', 'calc_x0y0', 'calc_y0', 'cost_s', 'cost_sxsy', 'cost_sy', 'cost_x0y0', 'cost_y0', 'cov_p', 'debug', 'ier', 'infodict', 'mesg', 'model_s', 'model_sxsy', 'model_sy', 'model_x0y0', 'model_y0', 'p', 'p0', 'plot', 'static_model', 'sx', 'sy', 'x0', 'y0']
ipdb> attr
'sy'
ipdb> obj.sx
56.08609594210083
ipdb> obj.sy
<jsonpickle.unpickler._IDProxy object at 0x7fa5ae504210>
ipdb> 
```
The `py/id` for `sy` is 1098, which is out of range by about 20, and strangely, the next highest `py/id` I can find in the .json is something like 587, which is a big gap. Maybe this is a hint.

I've worked around this in my code by indexing into `self.p` separately for both `sx` and `sy`:

```python
s, = abs(sls.p) # sls.p is a numpy array of length 1
sort.sls.sx, sort.sls.sy = s[0], s[0]
```

This gives them the same value but different ids, i.e. they're different objects, jsonpickle doesn't generate a proxy for `sy`, and the IndexError is avoided. I also found that if I cleaned up a few other unnecessary instances of numpy scalar ints/floats in my object and converted them to builtin ints/floats (or lists of ints/floats, etc.), that *also* fixed the issue.

I've attached a .json encoding of the `sort` object that triggers the issue. You'll probably have to grab a copy of my app https://github.com/spyke/spyke to get far enough in decoding it that the IndexError is triggered. It can also be visually inspected. It uses simplejson's indentation, about 13000 lines long:

[mspacek_IndexError_bug_182.zip](https://github.com/jsonpickle/jsonpickle/files/3734117/mspacek_IndexError_bug_182.zip)

I tried creating something similar in a fairly minimal example (see `jsonpickle_debug.py` in the attached .zip) with lots of deep nesting and numpy scalars set by reference, and reference counts way up into the 10s of thousands, but I haven't had any success in reproducing the error.

Please let me know if there's anything specific I can do to help debug. Might be easier that way than forcing others to inspect my app. The last commit of my app that triggered the bug was https://github.com/spyke/spyke/commit/0711b617851bc08e319e79dad73a8e13a659c2d5 . The one after it fixed it. Subsequent commits on their own also fixed it.

I could also include a Python2 pickle of the same object, generated using cPickle, which decodes error-free in Python2.

**Comment by mspacek** [comment]
@davvid just FYI, https://github.com/jsonpickle/jsonpickle/issues/246 seems to be reporting a failure at the same place in `unpickler.py`. I don't know if the cause is similar.

**Comment by davvid** [comment]
Yeah, these are all the same fundamental issue as described in #246. I don't have much time to work on a v2 this year so I'd be pretty stoked to see some experimental versions from the community.

These days I don't like the multi-backend feature either. We should just use simplejson/json and nothing more, so that's another thing for v2.

One reason the multi-backend thing exists is that it allowed having json files with comments to get gracefully loaded by demjson, and in hindsight that was a mistake.

The numpy id() thing is pretty interesting -- in practice I think it would cause it to export more than expected, but it's possible it could have other effects.

As described in #246 a good place to start reworking the approach would be to read the cpickle code.

Sorry for not having much jp time lately, but I do believe there's improvements that we will be able to achieve eventually, especially if someone comes up with something experimental.

**Comment by xentycz** [comment]
Hi, we're currently trying to use **jsonpickle** in one project I'm working on and I think we have run into this issue (or something very similar) as well. We're currently trying to evaluate what to do next. In the meantime, I was able to come up with a pretty minimalist piece of code that is failing with an `IndexError: list index out of range` error at least on my side. It seems, that the problem lies somewhere in the numpy array ids logic like @mspacek mentioned. Here is the code if anybody wants to take a look:

```
import numpy as np

import jsonpickle
import jsonpickle.ext.numpy as jsonpickle_numpy


class Object1:
    def __init__(self, spots):
        if spots is None:
            spots = {}
        self.spots = spots


class Object2:
    def __init__(self):
        self.a = 12
        self.b = 8


if __name__ == "__main__":
    jsonpickle_numpy.register_handlers()
    jsonpickle.set_preferred_backend("json")

    larger_numpy_array = np.array(
        [
            [6.63207911e00, -1.25597576e02, -1.24453443e-03],
            [-1.01356520e01, -1.25654364e02, -1.25025794e-03],
            [-1.01260821e01, -1.28480009e02, -1.30673898e-03],
            [6.63781893e00, -1.28423234e02, -1.30101209e-03],
            [6.63207911e00, -1.25597576e02, -1.24453443e-03],
        ]
    )
    object1 = Object1(spots={"9E": larger_numpy_array[:, :2]})
    object2 = Object2()

    original_object = [object1, object2, object2]

    json_string = jsonpickle.encode(original_object)
    rebuilt_object = jsonpickle.decode(json_string)
```

**Comment by stefan6419846** [comment]
> i get `IndexError: list index out of range` when i modify the json

What would be your expected output in this case? Tampering with the output like this, basically removing referenced objects, does not allow for clean deserialization, so there is not much `jsonpickle` can do about it in my opinion.

**Comment by milahu** [comment]
> removing referenced objects

this is not necessary to reproduce the error. example:

<details>

```py
#! /usr/bin/env python3

#! /usr/bin/env nix-shell
#! nix-shell -p python3 python3.pkgs.jsonpickle -i python3

import json, jsonpickle

class X:
  def __init__(self, data=None):
    self.data = data

a = X()
a.data = a # circular reference

b = X()
b.data = b # circular reference

data1 = [a, b]
text1 = jsonpickle.encode(data1)
print(f"data1:\n{data1}")
print(f"text1:\n{text1}")

data2 = json.loads(text1)
data2 = data2[1:] # remove data2[0]
text2 = json.dumps(data2)
print(f"text2:\n{text2}")

data3 = jsonpickle.decode(text2)
print(f"data3:\n{data3}")
```


</details>

output:

```
data1:
[<__main__.X object at 0x7fd5ce2f90c0>, <__main__.X object at 0x7fd5ce2f88e0>]
text1:
[{"py/object": "__main__.X", "data": {"py/id": 1}}, {"py/object": "__main__.X", "data": {"py/id": 2}}]
text2:
[{"py/object": "__main__.X", "data": {"py/id": 2}}]
IndexError: list index out of range
```

i would expect that the addressing is position-independent. example:


```
text2:
[{"py/self": 2, "py/object": "__main__.X", "data": {"py/id": 2}}]
```

**Comment by Theelx** [comment]
Addressing is not position-independent.

**Comment by annapods** [comment]
Hi,

I had the same index out of range error appear very randomly from one day to the next on a bit of script that used to work with no problem.

I'm pickling an object that itself references objects that themselves... etc. Changing from encode/decode to unpickler like in [this example](https://github.com/jsonpickle/jsonpickle/commit/eb505c02d5721c1b67cef523c20515b559075d70) makes the error go away, but doesn't actually give me the objects.

If `reset=True`, the error reappears.

Is this an error on my end, or am I missing something?

Here's a code example:
```
class Class1:
    def __init__(self):
        self.a = {1: Class2()}
    def __str__(self) -> str:
        return str(self.a)

class Class2:
    def __init__(self):
        self.b = [2, 3]
    def __str__(self) -> str:
        return str(self.b)


import jsonpickle
import json
obj = Class1()
doc = jsonpickle.dumps(obj)
unpickler = jsonpickle.unpickler.Unpickler()
jsonpickle.loads(doc, context=unpickler)
clone = json.loads(doc, object_hook=lambda x: unpickler.restore(x, reset=False))
print(obj)
```

The result:
```{1: <__main__.Class2 object at 0x74710d718a60>}```
