### ISSUE TITLE
jsonpickle doesn't work with sgdclassifier

### ISSUE THREAD

**Issue by fedorzh** [jsonpickle/jsonpickle#184]
#### Description
Error given

#### Steps/Code to Reproduce
```python
import numpy as np
import jsonpickle
from sklearn.linear_model import SGDClassifier
clf = SGDClassifier(loss='log', penalty='l2', alpha=1e-4, n_iter=100, random_state=42, n_jobs=-1)
np.random.seed(13)
x = np.random.rand(10,5)
y = np.random.randint(low=0, high=2, size=10)
clf.fit(x, y)
clf2 = jsonpickle.decode(jsonpickle.encode(clf))
```

#### Expected Results
get the same clf2 as clf

#### Actual Results

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "python2.7/site-packages/jsonpickle/__init__.py", line 149, in decode
    return unpickler.decode(string, backend=backend, keys=keys)
  File "python2.7/site-packages/jsonpickle/unpickler.py", line 26, in decode
    return context.restore(backend.decode(string), reset=reset)
  File "python2.7/site-packages/jsonpickle/unpickler.py", line 127, in restore
    value = self._restore(obj)
  File "python2.7/site-packages/jsonpickle/unpickler.py", line 169, in _restore
    return restore(obj)
  File "python2.7/site-packages/jsonpickle/unpickler.py", line 283, in _restore_object
    return self._restore_object_instance(obj, cls)
  File "python2.7/site-packages/jsonpickle/unpickler.py", line 348, in _restore_object_instance
    return self._restore_object_instance_variables(obj, instance)
  File "python2.7/site-packages/jsonpickle/unpickler.py", line 393, in _restore_object_instance_variables
    instance = self._restore_state(obj, instance)
  File "python2.7/site-packages/jsonpickle/unpickler.py", line 398, in _restore_state
    state = self._restore(obj[tags.STATE])
  File "python2.7/site-packages/jsonpickle/unpickler.py", line 169, in _restore
    return restore(obj)
  File "python2.7/site-packages/jsonpickle/unpickler.py", line 451, in _restore_dict
    data[k] = self._restore(v)
  File "python2.7/site-packages/jsonpickle/unpickler.py", line 169, in _restore
    return restore(obj)
  File "python2.7/site-packages/jsonpickle/unpickler.py", line 192, in _restore_reduce
    if f == tags.NEWOBJ or f.__name__ == '__newobj__':
AttributeError: 'dict' object has no attribute '__name__'
```

#### Versions
```
>>> import sys; print("Python", sys.version)
('Python', '2.7.8 (default, Aug  3 2017, 16:13:26) \n[GCC 5.4.0 20160609]')
>>> import numpy; print("NumPy", numpy.__version__)
('NumPy', '1.13.1')
>>> import scipy; print("SciPy", scipy.__version__)
('SciPy', '0.19.1')
>>> import sklearn; print("Scikit-Learn", sklearn.__version__)
('Scikit-Learn', '0.19.0')
```

**Comment by davvid** [comment]
You may need to load the numpy extension.

Please see http://jsonpickle.readthedocs.io/en/latest/extensions.html for how to do that.

Feel free to reopen this issue if you're able to help reproduce the issue in unittest form.  `tests/numpy_test.py` is where we keep the numpy tests.  There are certainly lots of libraries that can pose challenging.

A good place to start is to run `make test` and see if the current tests pass in your environment.

We use `nosetests`, so `sudo apt-get install python-nose` (or the python3 one) will be needed to run the test suite.  I use a bunch of virtualenvs so my usual workflow is often:
```
vx env27 make test &&
vx env35 make test &&
vx env36 make test
```

where the env dirs are virtualenvs for the various python versions that I've setup beforehand and vx[1] is a simple virtualenv command runner.  The quickest way to build and test your own env is to do:

```
virtualenv env
vx env pip install -r requirements-dev.txt
vx env make test`
```

Let me know if the numpy extensions help at all.  We should probably tag and relese what's in master since there are some improvements near the code in the backtrace, so it might be worth trying what's in master (it's hard to tell whether or not the backtrace is using an older release).

[1] https://github.com/davvid/vx

**Comment by fedorzh** [comment]
If I load the extensions, a different error appears:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "python2.7/site-packages/jsonpickle/__init__.py", line 149, in decode
    return unpickler.decode(string, backend=backend, keys=keys)
  File "python2.7/site-packages/jsonpickle/unpickler.py", line 26, in decode
    return context.restore(backend.decode(string), reset=reset)
  File "python2.7/site-packages/jsonpickle/unpickler.py", line 127, in restore
    value = self._restore(obj)
  File "python2.7/site-packages/jsonpickle/unpickler.py", line 169, in _restore
    return restore(obj)
  File "python2.7/site-packages/jsonpickle/unpickler.py", line 283, in _restore_object
    return self._restore_object_instance(obj, cls)
  File "python2.7/site-packages/jsonpickle/unpickler.py", line 348, in _restore_object_instance
    return self._restore_object_instance_variables(obj, instance)
  File "python2.7/site-packages/jsonpickle/unpickler.py", line 393, in _restore_object_instance_variables
    instance = self._restore_state(obj, instance)
  File "python2.7/site-packages/jsonpickle/unpickler.py", line 398, in _restore_state
    state = self._restore(obj[tags.STATE])
  File "python2.7/site-packages/jsonpickle/unpickler.py", line 169, in _restore
    return restore(obj)
  File "python2.7/site-packages/jsonpickle/unpickler.py", line 451, in _restore_dict
    data[k] = self._restore(v)
  File "python2.7/site-packages/jsonpickle/unpickler.py", line 169, in _restore
    return restore(obj)
  File "python2.7/site-packages/jsonpickle/unpickler.py", line 275, in _restore_object
    instance = handler(self).restore(obj)
  File "python2.7/site-packages/jsonpickle/ext/numpy.py", line 258, in restore
    base = self.context.restore(base, reset=False)
  File "python2.7/site-packages/jsonpickle/unpickler.py", line 127, in restore
    value = self._restore(obj)
  File "python2.7/site-packages/jsonpickle/unpickler.py", line 169, in _restore
    return restore(obj)
  File "python2.7/site-packages/jsonpickle/unpickler.py", line 275, in _restore_object
    instance = handler(self).restore(obj)
  File "python2.7/site-packages/jsonpickle/ext/numpy.py", line 255, in restore
    arr = super(NumpyNDArrayHandlerView, self).restore(data)
  File "python2.7/site-packages/jsonpickle/ext/numpy.py", line 161, in restore
    buffer = b64decode(values)
  File "python2.7/site-packages/jsonpickle/util.py", line 516, in b64decode
    return base64.b64decode(payload)
  File "python2.7/base64.py", line 73, in b64decode
    return binascii.a2b_base64(s)
TypeError: must be string or buffer, not float
```

About the release:
```
>>> print("Jsonpickle", jsonpickle.__version__)
('Jsonpickle', '0.9.5')
```

**Comment by davvid** [comment]
Thanks, I have a fix I'll push up shortly.  This looks like an edge case.. unfortunately I'm unable to reproduce it with just numpy, but I added scikit to the test suite nonetheless.

**Comment by fedorzh** [comment]
Thank you for such a quick fix

**Comment by lesteve** [comment]
This seems to happen for 0d numpy arrays, here is a reproducer with only numpy:

```py
import jsonpickle
import jsonpickle.ext.numpy as jsonpickle_numpy
jsonpickle_numpy.register_handlers()

import numpy as np
jsonpickle.decode(jsonpickle.encode(np.array(0.)))
```
