### ISSUE TITLE
Basic operations fail if supplementary JSON libs aren't installed

### ISSUE THREAD

**Issue by jaraco** [jsonpickle/jsonpickle#217]
While troubleshooting #216, when testing against the master branch, apparently a regression since 0.9.6, I see:

```
celery-schedulers master $ cat test-schedule-entry.py
import celery.schedules, celery.beat, jsonpickle
schedule = celery.schedules.crontab(0, 12)
entry = celery.beat.ScheduleEntry(schedule=schedule)
data = jsonpickle.dumps(entry)
print(data)
renew = jsonpickle.loads(data)
celery-schedulers master $ rwt -q 'git+https://github.com/jsonpickle/jsonpickle' 'celery<4' -- -i test-schedule-entry.py
Traceback (most recent call last):
  File "test-schedule-entry.py", line 4, in <module>
    data = jsonpickle.dumps(entry)
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-q7zv79uy/jsonpickle/pickler.py", line 76, in encode
    return backend.encode(context.flatten(value, reset=reset))
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-q7zv79uy/jsonpickle/backend.py", line 165, in encode
    raise e
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-q7zv79uy/jsonpickle/backend.py", line 162, in encode
    return self.backend_encode(name, obj)
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-q7zv79uy/jsonpickle/backend.py", line 173, in backend_encode
    return self._encoders[name](*encoder_args, **encoder_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
```

**Comment by jaraco** [comment]
The object that's not encoded is `b'B+IIGQ8HHQsaoQ=='`, which is part of a `datetime.datetime` reduction.

**Comment by jaraco** [comment]
I can replicate the issue with a simple datetime.datetime object:

```
celery-schedulers master $ cat ~/p/jsonpickle/test-issue-217.py
import jsonpickle
import datetime

jsonpickle.dumps(datetime.datetime.now())
celery-schedulers master $ rwt -q 'git+https://github.com/jsonpickle/jsonpickle' -- ~/p/jsonpickle/test-issue-217.py
Traceback (most recent call last):
  File "/Users/jaraco/p/jsonpickle/test-issue-217.py", line 4, in <module>
    jsonpickle.dumps(datetime.datetime.now())
  File "/Users/jaraco/Dropbox/code/public/jsonpickle/jsonpickle/pickler.py", line 76, in encode
    return backend.encode(context.flatten(value, reset=reset))
  File "/Users/jaraco/Dropbox/code/public/jsonpickle/jsonpickle/backend.py", line 165, in encode
    raise e
  File "/Users/jaraco/Dropbox/code/public/jsonpickle/jsonpickle/backend.py", line 162, in encode
    return self.backend_encode(name, obj)
  File "/Users/jaraco/Dropbox/code/public/jsonpickle/jsonpickle/backend.py", line 173, in backend_encode
    return self._encoders[name](*encoder_args, **encoder_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
```

**Comment by jaraco** [comment]
Here's something interesting - the issue only occurs when I create the virtualenv; if I let tox create the virtualenv according to tox.ini, the error doesn't occur. It seems there's something about the test environment that's masking the error.

**Comment by jaraco** [comment]
Bisect implicates 3f87b87a.

```
jsonpickle master $ git bisect run .tox/python/bin/python ~/draft/test-issue-217.py
running .tox/python/bin/python /Users/jaraco/draft/test-issue-217.py
Bisecting: 12 revisions left to test after this (roughly 4 steps)
[c4a36426bf25c4a85b3c23739d9955778b65f022] tox: add Python 3.7
running .tox/python/bin/python /Users/jaraco/draft/test-issue-217.py
Traceback (most recent call last):
  File "/Users/jaraco/draft/test-issue-217.py", line 4, in <module>
    jsonpickle.dumps(datetime.datetime.now())
  File "/Users/jaraco/Dropbox/code/public/jsonpickle/jsonpickle/pickler.py", line 76, in encode
    return backend.encode(context.flatten(value, reset=reset))
  File "/Users/jaraco/Dropbox/code/public/jsonpickle/jsonpickle/backend.py", line 165, in encode
    raise e
  File "/Users/jaraco/Dropbox/code/public/jsonpickle/jsonpickle/backend.py", line 162, in encode
    return self.backend_encode(name, obj)
  File "/Users/jaraco/Dropbox/code/public/jsonpickle/jsonpickle/backend.py", line 173, in backend_encode
    return self._encoders[name](*encoder_args, **encoder_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
Bisecting: 6 revisions left to test after this (roughly 3 steps)
[9b3b7b9959fad2c1ef8261b1b8c7c3ea5f2b189b] pickler: update doctest for the max_depth change
running .tox/python/bin/python /Users/jaraco/draft/test-issue-217.py
Bisecting: 3 revisions left to test after this (roughly 2 steps)
[3c6eac32de526827cd1340117a2e105472775afb] jsonpickle: update copyright notices for 2018
running .tox/python/bin/python /Users/jaraco/draft/test-issue-217.py
Bisecting: 1 revision left to test after this (roughly 1 step)
[402049183746c2e61729ceaf8b9ef543ec46e947] tests: simplify util_test imports
running .tox/python/bin/python /Users/jaraco/draft/test-issue-217.py
Bisecting: 0 revisions left to test after this (roughly 0 steps)
[3f87b87a87fc4c5bfe2ce5d7d59a40ab9ddc35cd] jsonpickle: drop support for Python 2.6 and 3.3
running .tox/python/bin/python /Users/jaraco/draft/test-issue-217.py
Traceback (most recent call last):
  File "/Users/jaraco/draft/test-issue-217.py", line 4, in <module>
    jsonpickle.dumps(datetime.datetime.now())
  File "/Users/jaraco/Dropbox/code/public/jsonpickle/jsonpickle/pickler.py", line 76, in encode
    return backend.encode(context.flatten(value, reset=reset))
  File "/Users/jaraco/Dropbox/code/public/jsonpickle/jsonpickle/backend.py", line 165, in encode
    raise e
  File "/Users/jaraco/Dropbox/code/public/jsonpickle/jsonpickle/backend.py", line 162, in encode
    return self.backend_encode(name, obj)
  File "/Users/jaraco/Dropbox/code/public/jsonpickle/jsonpickle/backend.py", line 173, in backend_encode
    return self._encoders[name](*encoder_args, **encoder_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
3f87b87a87fc4c5bfe2ce5d7d59a40ab9ddc35cd is the first bad commit
commit 3f87b87a87fc4c5bfe2ce5d7d59a40ab9ddc35cd
Author: David Aguilar <davvid@gmail.com>
Date:   Sat Jun 23 12:09:12 2018 -0700

    jsonpickle: drop support for Python 2.6 and 3.3

    jsonpickle now supports Python 2.7 and 3.4+ only.

    Signed-off-by: David Aguilar <davvid@gmail.com>

:100644 100644 8e647d452430e782f7390df9a55cb9c5d4ded002 2bec6a522c3e09dd2d7ee304c08038aea79d5b0c M      README.rst
:040000 040000 32444d50ccc4b0907aa3c301366179dc6ff70d07 a81912afc10530f740de542f0f631c4cb5986dca M      docs
:040000 040000 f16bc92745c8f9f5f0c26477caadb107d8dfaae1 1a3a3244e70d30b291ae049ca2b81dd3777dd259 M      jsonpickle
:040000 040000 2fc696421d568eaaacd64dfb73316f60994570b5 3884879f7a8de2b573c6bd9fcc81e731e7772141 M      tests
:100644 100644 33497ef12e193aa8cfb523f73696af43d8bcdc2a b382eda25703f7adc8603b4d3da1570187f1c369 M      tox.ini
bisect run success
```

**Comment by jaraco** [comment]
The issue is the inclusion/exclusion of `simplejson`. Because the test suite includes `simplejson`, it masks the error on stdlib json.

**Comment by jaraco** [comment]
@davvid In my fork, I've pushed 07476a1 which demonstrates the failure of the test suite to test the most basic usage without supplementary JSON libs. It adds new tox envs with the 'libs' factor that test that mode. Without that factor, the tests are run without JSON libs and there are many failures. Would you be willing to take this one from here?

**Comment by davvid** [comment]
Awesome sleuthing...  Thanks @jaraco  I'm able to reproduce the error locally now.  I actually think I have a fix too. I'll push up a commit shortly, please try it out, I definitely appreciate another set of eyes on it.

**Comment by jaraco** [comment]
Looks great! Thanks for the quick turnaround. I might wish to tweak/hone things further, but the changes look stable and address the issue properly, so I'm quite happy with it.
