### ISSUE TITLE
jsonpickle.decode does not work for immutable fields in dataclasses

### ISSUE THREAD

**Issue by SaschaSchlemmer** [jsonpickle/jsonpickle#240]
When playing around with the new `dataclass` functionality in python 3.7 I found that jsonpickle does not play with immutable `field`s.

Minimal example:

    @dataclass(frozen=True)
    class c():
        x:str

then 

    jsonpickle.decode(jsonpickle.encode(c(1))) 

throws an `FrozenInstanceError` during the decode step.

**Comment by svermeulen** [comment]
jsonpickle appears to use `setattr` which is not allowed by frozen dataclass.  I think `object.__setattr__` though

**Comment by nakulcr7** [comment]
@svermeulen, is there anyway you got around this limitation?

**Comment by svermeulen** [comment]
Yeah, the way I did it was I just didn't use `frozen` and instead had a base class that made my classes immutable.  For example:  https://gist.github.com/svermeulen/2d5f97ffe190d6db7490e072890c4112

Note that the base class in this gist does other things too that you might not care about like type checking

**Comment by bsundaram1** [comment]
I'm still getting the same error with the example above while using jsonpickle v2.2.0:
```python3
@dataclass(frozen=True)
class C:
    x:str

instance = C(x='hello')
enc = jsonpickle.encode(x)
dec = jsonpickle.decode(enc)
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/bb/lib/python3.9/site-packages/jsonpickle/unpickler.py", line 85, in decode
    return context.restore(data, reset=reset, classes=classes)
  File "/opt/bb/lib/python3.9/site-packages/jsonpickle/unpickler.py", line 355, in restore
    value = self._restore(obj)
  File "/opt/bb/lib/python3.9/site-packages/jsonpickle/unpickler.py", line 337, in _restore
    return restore(obj)
  File "/opt/bb/lib/python3.9/site-packages/jsonpickle/unpickler.py", line 756, in _restore_object
    return self._restore_object_instance(obj, cls, class_name)
  File "/opt/bb/lib/python3.9/site-packages/jsonpickle/unpickler.py", line 732, in _restore_object_instance
    instance = self._restore_object_instance_variables(obj, instance)
  File "/opt/bb/lib/python3.9/site-packages/jsonpickle/unpickler.py", line 666, in _restore_object_instance_variables
    instance = self._restore_from_dict(obj, instance)
  File "/opt/bb/lib/python3.9/site-packages/jsonpickle/unpickler.py", line 617, in _restore_from_dict
    setattr(instance, k, value)
  File "<string>", line 4, in __setattr__
dataclasses.FrozenInstanceError: cannot assign to field 'x'
```

I'm not quite sure why execution even reaches L617 in this case when the expected behavior is for it to enter the else block here - https://github.com/jsonpickle/jsonpickle/blob/33921686003c534c51a16d71da605b030eee891b/jsonpickle/unpickler.py#L626
