### ISSUE TITLE
[bug] clonefactory causes id reference issues

### ISSUE THREAD

**Issue by woutdenolf** [jsonpickle/jsonpickle#253]
python: 3.6
jsonpickle: 1.1
bug: whenever I see `CloneFactory` and `py/id` in the flattened result, unpickling often fails (in different ways depending on the situation)

Here is one way to make it fail:
```python
import jsonpickle
import collections

jsonpickle.set_preferred_backend('json')
jsonpickle.set_encoder_options('json', indent=2)

class Class(object):
    def __init__(self,**kwargs):
        self.dic = kwargs
    def __getstate__(self):
        return {'dic': self.dic}
    def __setstate__(self, state):
        self.dic = state['dic']
    def __eq__(self,other):
        return self.dic == other.dic

def defaultfunc():
    return Class(default=True)

a = Class(a=1, b=2)
b = collections.defaultdict(defaultfunc)
data1 = Class(b=b, x=a, y=a)
s = jsonpickle.dumps(data1)
print(s)
data2 = jsonpickle.loads(s)
assert(data1==data2)
```
Result:
```
{
  "py/object": "__main__.Class",
  "py/state": {
    "dic": {
      "b": {
        "py/object": "collections.defaultdict",
        "default_factory": {
          "py/object": "jsonpickle.handlers.CloneFactory",
          "exemplar": {
            "py/object": "__main__.Class",
            "py/state": {
              "dic": {
                "default": true
              }
            }
          }
        }
      },
      "x": {
        "py/object": "__main__.Class",
        "py/state": {
          "dic": {
            "a": 1,
            "b": 2
          }
        }
      },
      "y": {
        "py/id": 5
      }
    }
  }
}
Traceback (most recent call last):
  File "test.py", line 25, in <module>
    data2 = jsonpickle.loads(s)
  File ".../jsonpickle/unpickler.py", line 40, in decode
    return context.restore(data, reset=reset, classes=classes)
  File ".../jsonpickle/unpickler.py", line 147, in restore
    self._swap_proxies()
  File ".../jsonpickle/unpickler.py", line 165, in _swap_proxies
    method(obj, attr, proxy)
  File ".../jsonpickle/unpickler.py", line 100, in _obj_setvalue
    obj[idx] = proxy.get()
  File ".../jsonpickle/unpickler.py", line 92, in get
    return self._objs[self._index]
IndexError: list index out of range
```

**Comment by davvid** [comment]
You need to include `sort_keys=True` in the call to `set_encoder_options(...)` otherwise the encode/decode cycle will iterate process the objects in the wrong order.  This will be improved in the v2 encoder.
