### ISSUE TITLE
Issue decoding Pandas dataframe

### ISSUE THREAD

**Issue by misantroop** [jsonpickle/jsonpickle#266]
I'm unable to reproduce a short code sample at the moment. 
First part is the output from Pandas.

```
[Index(['contractAmbig', 'contractComboLegs', 'contractComboLegsDescrip',
       'contractConId', 'contractCurrency', 'contractDeltaNeutralContract',
       'contractExchange', 'contractIncludeExpired',
       'contractLastTradeDateOrContractMonth', 'contractLocalSymbol',
       ...
       'orderTrailingPercent', 'orderTransmit', 'orderTriggerMethod',
       'orderTriggerPrice', 'orderVolatility', 'orderVolatilityType',
       'orderWhatIf', 'sig', 'status', 'validate'],
      dtype='object', length=147), 'contractAmbig']

Traceback (most recent call last):
  File "C:\WRK\trd.py", line 32, in <module>
    trd = pickleNQ.take('sbqNq')
  File "C:\WRK\ipo.py", line 359, in take
    return jsonpickle.decode(self.fern.decrypt(jar.read()))
  File "C:\Python\lib\site-packages\jsonpickle\unpickler.py", line 41, in decode
    return context.restore(data, reset=reset, classes=classes)
  File "C:\Python\lib\site-packages\jsonpickle\unpickler.py", line 150, in restore
    value = self._restore(obj)
  File "C:\Python\lib\site-packages\jsonpickle\unpickler.py", line 207, in _restore
    return restore(obj)
  File "C:\Python\lib\site-packages\jsonpickle\unpickler.py", line 323, in _restore_object
    return self._restore_object_instance(obj, cls)
  File "C:\Python\lib\site-packages\jsonpickle\unpickler.py", line 390, in _restore_object_instance
    return self._restore_object_instance_variables(obj, instance)
  File "C:\Python\lib\site-packages\jsonpickle\unpickler.py", line 440, in _restore_object_instance_variables
    instance = self._restore_from_dict(obj, instance)
  File "C:\Python\lib\site-packages\jsonpickle\unpickler.py", line 408, in _restore_from_dict
    value = self._restore(v)
  File "C:\Python\lib\site-packages\jsonpickle\unpickler.py", line 207, in _restore
    return restore(obj)
  File "C:\Python\lib\site-packages\jsonpickle\unpickler.py", line 323, in _restore_object
    return self._restore_object_instance(obj, cls)
  File "C:\Python\lib\site-packages\jsonpickle\unpickler.py", line 390, in _restore_object_instance
    return self._restore_object_instance_variables(obj, instance)
  File "C:\Python\lib\site-packages\jsonpickle\unpickler.py", line 452, in _restore_object_instance_variables
    instance = self._restore_state(obj, instance)
  File "C:\Python\lib\site-packages\jsonpickle\unpickler.py", line 457, in _restore_state
    state = self._restore(obj[tags.STATE])
  File "C:\Python\lib\site-packages\jsonpickle\unpickler.py", line 207, in _restore
    return restore(obj)
  File "C:\Python\lib\site-packages\jsonpickle\unpickler.py", line 514, in _restore_dict
    data[k] = self._restore(v)
  File "C:\Python\lib\site-packages\jsonpickle\unpickler.py", line 207, in _restore
    return restore(obj)
  File "C:\Python\lib\site-packages\jsonpickle\unpickler.py", line 323, in _restore_object
    return self._restore_object_instance(obj, cls)
  File "C:\Python\lib\site-packages\jsonpickle\unpickler.py", line 390, in _restore_object_instance
    return self._restore_object_instance_variables(obj, instance)
  File "C:\Python\lib\site-packages\jsonpickle\unpickler.py", line 452, in _restore_object_instance_variables
    instance = self._restore_state(obj, instance)
  File "C:\Python\lib\site-packages\jsonpickle\unpickler.py", line 457, in _restore_state
    state = self._restore(obj[tags.STATE])
  File "C:\Python\lib\site-packages\jsonpickle\unpickler.py", line 207, in _restore
    return restore(obj)
  File "C:\Python\lib\site-packages\jsonpickle\unpickler.py", line 499, in _restore_tuple
    return tuple([self._restore(v) for v in obj[tags.TUPLE]])
  File "C:\Python\lib\site-packages\jsonpickle\unpickler.py", line 499, in <listcomp>
    return tuple([self._restore(v) for v in obj[tags.TUPLE]])
  File "C:\Python\lib\site-packages\jsonpickle\unpickler.py", line 207, in _restore
    return restore(obj)
  File "C:\Python\lib\site-packages\jsonpickle\unpickler.py", line 487, in _restore_list
    children = [self._restore(v) for v in obj]
  File "C:\Python\lib\site-packages\jsonpickle\unpickler.py", line 487, in <listcomp>
    children = [self._restore(v) for v in obj]
  File "C:\Python\lib\site-packages\jsonpickle\unpickler.py", line 207, in _restore
    return restore(obj)
  File "C:\Python\lib\site-packages\jsonpickle\unpickler.py", line 323, in _restore_object
    return self._restore_object_instance(obj, cls)
  File "C:\Python\lib\site-packages\jsonpickle\unpickler.py", line 390, in _restore_object_instance
    return self._restore_object_instance_variables(obj, instance)
  File "C:\Python\lib\site-packages\jsonpickle\unpickler.py", line 446, in _restore_object_instance_variables
    instance.append(self._restore(v))
  File "C:\Python\lib\site-packages\pandas\core\indexes\base.py", line 4012, in append
    raise TypeError('all inputs must be Index')
TypeError: all inputs must be Index
```

**Comment by RajaParikshit** [comment]
How you solve the problem

**Comment by misantroop** [comment]
Update to the latest commit from september and see if the problem persists.

**Comment by AlexZHENGH** [comment]
Hi, I am having the same problem here:

```python
import json
import pandas as pd
import numpy as np
import jsonpickle


class A:
    def __init__(self):
        self.pd = pd.DataFrame({
            'x': [1, 3, 4],
            'y': ['a', 'b', 'c']
        })
        self.np = np.array(
            [1, 3, 4, 5]
        )


if __name__ == "__main__":
    a = A()

    frozen = jsonpickle.encode(a)
    thawed = jsonpickle.decode(frozen)
    print(thawed)
```

The output is:

```
  File "~/.virtualenvs/python3.6/site-packages/pandas/core/indexes/base.py", line 4325, in append
    raise TypeError("all inputs must be Index")
TypeError: all inputs must be Index
```
I am using the newest version 1.3. Could you let me know how to save an instance with attributes of Pandas dataframe or Numpy array?

Thanks.

**Comment by misantroop** [comment]
You need to register the pandas extensions.

```
import json
import pandas as pd
import numpy as np
import jsonpickle
import jsonpickle.ext.pandas as jsonpickle_pd
jsonpickle_pd.register_handlers()
```

**Comment by AlexZHENGH** [comment]
Thanks! That works beautifully.
