### ISSUE TITLE
Cannot decode dataclass with default_factory

### ISSUE THREAD

**Issue by MicheleMannino** [jsonpickle/jsonpickle#273]

**Comment by MicheleMannino** [comment]
I'd like to create an instance of Test without specifying list or dictionary and using default_factory:

```
>>> from dataclasses import dataclass
>>> from dataclasses import field
>>> import jsonpickle
>>> import json
>>> 
>>> @dataclass
... class Test:
...     id: str = None
...     status: str = None
...     my_dict: dict = field(default_factory=dict)
...     my_list: list = field(default_factory=list)
... 
>>> jsonpickle.decode(json.dumps({'py/object': '__main__.Test'}))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/dataclasses.py", line 357, in wrapper
    result = user_function(self)
  File "<string>", line 2, in __repr__
AttributeError: 'Test' object has no attribute 'my_dict'
```

python: 3.7.3
jsonpickle==1.1

Thanks in advance.

**Comment by GeorgesAlkhouri** [comment]
Is there a work around to mediate this?

**Comment by Theelx** [comment]
I don't believe there's a workaround for this, sorry. I believe it would require a radical redesign of jsonpickle to support this kind of initialization, if I'm understanding it correctly. To clarify, you want jsonpickle to call `__init__` when decoding a class instance, right?

**Comment by AndreasGocht** [comment]
I just stumbled upon the same thing. I was changing the definition of a data class with a few defualt_factories:

old class:
```
@dataclass
class Test:
    A: int = 1
```
new class:
```
@dataclass
class Test:
    A: int = 1
    B: list = field(default_factory=list)
```
However, while the deserialization seems to work, the issues arise when using the new dataclass. A full example is written below.
After a brief look at the documentation, a custom Handler might be helpful for working around this.  I’ll have a look.

Best, 

Andreas.

```
#test.json
{
    "py/object": "__main__.Test",
    "A": 2
}
```
```
#test2.py
from dataclasses import dataclass, field
from typing import Any

import jsonpickle


@dataclass
class Test:
    A: int = 1
    B: list = field(default_factory=list)


with open("test.json", "r") as f:
    s = f.read()
    t = jsonpickle.decode(s)

t2 = Test()
print(t == t2)
```
```
❯ python test2.py
Traceback (most recent call last):
  File "/home/andreas/code/test-jsonpickle/test2.py", line 23, in <module>
    print(t == t2)
          ^^^^^^^
  File "<string>", line 4, in __eq__
AttributeError: 'Test' object has no attribute 'B'
```

**Comment by AndreasGocht** [comment]
I came up with a custom handler, which needs to be registered with each dataclass. Unfortunately, dataclasses are not a subclass of a generic type. There is only the `dataclasses.is_dataclass` check if an object is a dataclass, which would require checking each object during serialisation/deserialisation. I am not sure if this is a good idea.


```
from dataclasses import MISSING, fields
from jsonpickle.handlers import BaseHandler
from jsonpickle.unpickler import loadclass #loadclass is located in util in the current master branch.

class DataclassHandler(BaseHandler):
    def flatten(self, obj, data):
        for f in fields(obj):
            data[f.name] = self.context.flatten(getattr(obj, f.name))
        return data

    def restore(self, obj):
        cls = loadclass(obj["py/object"])
        tmp = {}
        for f in fields(cls):
            if f.name in obj:
                tmp[f.name] = self.context.restore(obj[f.name], reset=False)
            else:
                if f.default is not MISSING:
                    tmp[f.name] = f.default
                elif f.default_factory is not MISSING:
                    tmp[f.name] = f.default_factory()
                else:
                    raise RuntimeError(
                        f"{f.name} of {cls} is missing and not default constructable"
                    )
        return cls(**tmp)
```
