### ISSUE TITLE
Failed test with python 3.8: test_thing_with_fd, test_list_with_fd, test_dict_with_fd

### ISSUE THREAD

**Issue by mcepl** [jsonpickle/jsonpickle#281]
When packaging update for this project with Python 3.8 on openSUSE/Factory, I got this failed tests:

```
[   11s] =================================== FAILURES ===================================
[   11s] __________________ AdvancedObjectsTestCase.test_dict_with_fd ___________________
[   11s]
[   11s] self = <object_test.AdvancedObjectsTestCase testMethod=test_dict_with_fd>
[   11s]
[   11s]     def test_dict_with_fd(self):
[   11s]         fd = open(__file__, 'r')
[   11s]         fd.close()
[   11s]         obj = {'fd': fd}
[   11s]         jsonstr = jsonpickle.encode(obj)
[   11s]         newobj = jsonpickle.decode(jsonstr)
[   11s] >       self.assertEqual(None, newobj['fd'])
[   11s] E       AssertionError: None != <_io.TextIOWrapper object at 0x7f13d5ffa860>
[   11s]
[   11s] tests/object_test.py:405: AssertionError
[   11s] __________________ AdvancedObjectsTestCase.test_list_with_fd ___________________
[   11s]
[   11s] self = <object_test.AdvancedObjectsTestCase testMethod=test_list_with_fd>
[   11s]
[   11s]     def test_list_with_fd(self):
[   11s]         fd = open(__file__, 'r')
[   11s]         fd.close()
[   11s]         obj = [fd]
[   11s]         jsonstr = jsonpickle.encode(obj)
[   11s]         newobj = jsonpickle.decode(jsonstr)
[   11s] >       self.assertEqual([None], newobj)
[   11s]
[   11s] tests/object_test.py:389:
[   11s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
[   11s] /usr/lib64/python3.8/pprint.py:58: in pformat
[   11s]     return PrettyPrinter(indent=indent, width=width, depth=depth,
[   11s] /usr/lib64/python3.8/pprint.py:153: in pformat
[   11s]     self._format(object, sio, 0, 0, {}, 0)
[   11s] /usr/lib64/python3.8/pprint.py:170: in _format
[   11s]     rep = self._repr(object, context, level)
[   11s] /usr/lib64/python3.8/pprint.py:404: in _repr
[   11s]     repr, readable, recursive = self.format(object, context.copy(),
[   11s] /usr/lib64/python3.8/pprint.py:417: in format
[   11s]     return _safe_repr(object, context, maxlevels, level, self._sort_dicts)
[   11s] /usr/lib64/python3.8/pprint.py:560: in _safe_repr
[   11s]     orepr, oreadable, orecur = _safe_repr(o, context, maxlevels, level, sort_dicts)
[   11s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
[   11s]
[   11s] object = <[ValueError("I/O operation on uninitialized object") raised in repr()] TextIOWrapper object at 0x7f13d5ffa930>
[   11s] context = {139723169830656: 1}, maxlevels = None, level = 1, sort_dicts = True
[   11s]
[   11s]     def _safe_repr(object, context, maxlevels, level, sort_dicts):
[   11s]         typ = type(object)
[   11s]         if typ in _builtin_scalars:
[   11s]             return repr(object), True, False
[   11s]
[   11s]         r = getattr(typ, "__repr__", None)
[   11s]         if issubclass(typ, dict) and r is dict.__repr__:
[   11s]             if not object:
[   11s]                 return "{}", True, False
[   11s]             objid = id(object)
[   11s]             if maxlevels and level >= maxlevels:
[   11s]                 return "{...}", False, objid in context
[   11s]             if objid in context:
[   11s]                 return _recursion(object), False, True
[   11s]             context[objid] = 1
[   11s]             readable = True
[   11s]             recursive = False
[   11s]             components = []
[   11s]             append = components.append
[   11s]             level += 1
[   11s]             if sort_dicts:
[   11s]                 items = sorted(object.items(), key=_safe_tuple)
[   11s]             else:
[   11s]                 items = object.items()
[   11s]             for k, v in items:
[   11s]                 krepr, kreadable, krecur = _safe_repr(k, context, maxlevels, level, sort_dicts)
[   11s]                 vrepr, vreadable, vrecur = _safe_repr(v, context, maxlevels, level, sort_dicts)
[   11s]                 append("%s: %s" % (krepr, vrepr))
[   11s]                 readable = readable and kreadable and vreadable
[   11s]                 if krecur or vrecur:
[   11s]                     recursive = True
[   11s]             del context[objid]
[   11s]             return "{%s}" % ", ".join(components), readable, recursive
[   11s]
[   11s]         if (issubclass(typ, list) and r is list.__repr__) or \
[   11s]            (issubclass(typ, tuple) and r is tuple.__repr__):
[   11s]             if issubclass(typ, list):
[   11s]                 if not object:
[   11s]                     return "[]", True, False
[   11s]                 format = "[%s]"
[   11s]             elif len(object) == 1:
[   11s]                 format = "(%s,)"
[   11s]             else:
[   11s]                 if not object:
[   11s]                     return "()", True, False
[   11s]                 format = "(%s)"
[   11s]             objid = id(object)
[   11s]             if maxlevels and level >= maxlevels:
[   11s]                 return format % "...", False, objid in context
[   11s]             if objid in context:
[   11s]                 return _recursion(object), False, True
[   11s]             context[objid] = 1
[   11s]             readable = True
[   11s]             recursive = False
[   11s]             components = []
[   11s]             append = components.append
[   11s]             level += 1
[   11s]             for o in object:
[   11s]                 orepr, oreadable, orecur = _safe_repr(o, context, maxlevels, level, sort_dicts)
[   11s]                 append(orepr)
[   11s]                 if not oreadable:
[   11s]                     readable = False
[   11s]                 if orecur:
[   11s]                     recursive = True
[   11s]             del context[objid]
[   11s]             return format % ", ".join(components), readable, recursive
[   11s]
[   11s] >       rep = repr(object)
[   11s] E       ValueError: I/O operation on uninitialized object
[   11s]
[   11s] /usr/lib64/python3.8/pprint.py:569: ValueError
[   11s] __________________ AdvancedObjectsTestCase.test_thing_with_fd __________________
[   11s]
[   11s] self = <object_test.AdvancedObjectsTestCase testMethod=test_thing_with_fd>
[   11s]
[   11s]     def test_thing_with_fd(self):
[   11s]         fd = open(__file__, 'r')
[   11s]         fd.close()
[   11s]         obj = Thing(fd)
[   11s]         jsonstr = jsonpickle.encode(obj)
[   11s]         newobj = jsonpickle.decode(jsonstr)
[   11s] >       self.assertEqual(None, newobj.name)
[   11s] E       AssertionError: None != <_io.TextIOWrapper object at 0x7f13d5ffad40>
[   11s]
[   11s] tests/object_test.py:397: AssertionError
[   11s] =============================== warnings summary ===============================
[   11s] tests/numpy_test.py::NumpyTestCase::test_dtype_roundtrip
[   11s]   /home/abuild/rpmbuild/BUILD/jsonpickle-1.2/tests/numpy_test.py:55: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will
be understood as (type, (1,)) / '(1,)type'.
[   11s]     np.dtype('1i4', align=True),
[   11s]
[   11s] tests/numpy_test.py::NumpyTestCase::test_ndarray_roundtrip
[   11s]   /home/abuild/rpmbuild/BUILD/jsonpickle-1.2/jsonpickle/ext/numpy.py:298: UserWarning: ndarray is defined by reference to an object we do not know how to serialize. A deep copy is seriali
zed instead, breaking memory aliasing.
[   11s]     warnings.warn(msg)
[   11s]
[   11s] -- Docs: https://docs.pytest.org/en/latest/warnings.html
[   11s] ============ 3 failed, 240 passed, 39 skipped, 2 warnings in 1.29s =============
```

[Complete build logs with all details](https://github.com/jsonpickle/jsonpickle/files/3928169/_log.txt)

**Comment by davvid** [comment]
@mcepl @bmwiedemann thanks for the heads-up.  PR #292 should fix this.  Please test the `python3.8` branch from `git://githubb.com/davvid/jsonpickle.git` to verify.

@jaraco does 4e93850 look reasonable to you?  We don't currently do anything with `io.TextIOWrapper`, and the tests expect this behavior, so it seems like a decent workaround.

The new behavior in python3.8 is that it looks like it actually does roundtrip, whereas before the pickler would end up with `None` through an existing code path that it no longer hits.

Despite an object getting produced, the resulting object is dead and if you do `repr` or `str` on it then it throws an exception, so it doesn't seem like a useful result in general, so this new handler that transforms it to None seems sensible for python >= 3.8.

**Comment by jaraco** [comment]
Is there a reason not to supply the handler unconditionally, rather than rely on the code path that it happened to hit before?

**Comment by mcepl** [comment]
Thank you, works for me, package builds on openSUSE with Python 3.8.

**Comment by jaraco** [comment]
I wonder if this failed test is revealing something about an assumption that jsonpickle is making that it shouldn't or worse, a regression in Python 3.8 w.r.t. pickling TextIOWrapper objects generally.

Looking at what Python 3.7 and Python 3.8 do for pickling these objects, they both raise similar exceptions:

```
draft $ python3.8 -c "import pickle, io; pickle.dumps(io.open('jpformat.py'))"                                                                                            
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: cannot pickle '_io.TextIOWrapper' object
draft $ python3.7 -c "import pickle, io; pickle.dumps(io.open('jpformat.py'))"                                                                                            
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: cannot serialize '_io.TextIOWrapper' object
```

I'm inclined to suggest that jsonpickle should fail with a similar exception (though I don't feel strongly about it).
