### ISSUE TITLE
AttributeError: 'Int64' object attribute '_type_marker' is read-only

### ISSUE THREAD

**Issue by DeveloperAnonymous** [jsonpickle/jsonpickle#422]
**Python Version:** 3.10.8
**Jsonpickle Version:** 3.0.0
**OS:** Docker, python:3.10-slim (Debian GNU/Linux 11)
**Code:** https://github.com/BattleBanana/BattleBanana/blob/master/dueutil/game/players.py#L481-L488
**Stacktrace:** 
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "/usr/src/app/run.py", line 293, in on_message
    await events.on_message_event(message)
  File "/usr/src/app/dueutil/events.py", line 92, in on_message_event
    await message_event(ctx)
  File "/usr/src/app/dueutil/events.py", line 14, in __call__
    if await listener(ctx):
  File "/usr/src/app/dueutil/game/game.py", line 249, in on_message
    player = players.find_player(message.author.id)
  File "/usr/src/app/dueutil/game/players.py", line 472, in find_player
    elif load_player(user_id):
  File "/usr/src/app/dueutil/game/players.py", line 486, in load_player
    loaded_player = jsonpickle.decode(player_data)
  File "/usr/local/lib/python3.10/site-packages/jsonpickle/unpickler.py", line 88, in decode
    return context.restore(data, reset=reset, classes=classes)
  File "/usr/local/lib/python3.10/site-packages/jsonpickle/unpickler.py", line 362, in restore
    value = self._restore(obj)
  File "/usr/local/lib/python3.10/site-packages/jsonpickle/unpickler.py", line 344, in _restore
    return restore(obj)
  File "/usr/local/lib/python3.10/site-packages/jsonpickle/unpickler.py", line 768, in _restore_object
    return self._restore_object_instance(obj, cls, class_name)
  File "/usr/local/lib/python3.10/site-packages/jsonpickle/unpickler.py", line 744, in _restore_object_instance
    instance = self._restore_object_instance_variables(obj, instance)
  File "/usr/local/lib/python3.10/site-packages/jsonpickle/unpickler.py", line 690, in _restore_object_instance_variables
    instance = self._restore_state(obj, instance)
  File "/usr/local/lib/python3.10/site-packages/jsonpickle/unpickler.py", line 649, in _restore_state
    state = self._restore(obj[tags.STATE])
  File "/usr/local/lib/python3.10/site-packages/jsonpickle/unpickler.py", line 344, in _restore
    return restore(obj)
  File "/usr/local/lib/python3.10/site-packages/jsonpickle/unpickler.py", line 820, in _restore_dict
    data[k] = self._restore(v)
  File "/usr/local/lib/python3.10/site-packages/jsonpickle/unpickler.py", line 344, in _restore
    return restore(obj)
  File "/usr/local/lib/python3.10/site-packages/jsonpickle/unpickler.py", line 427, in _restore_list
    children = [self._restore(v) for v in obj]
  File "/usr/local/lib/python3.10/site-packages/jsonpickle/unpickler.py", line 427, in <listcomp>
    children = [self._restore(v) for v in obj]
  File "/usr/local/lib/python3.10/site-packages/jsonpickle/unpickler.py", line 344, in _restore
    return restore(obj)
  File "/usr/local/lib/python3.10/site-packages/jsonpickle/unpickler.py", line 768, in _restore_object
    return self._restore_object_instance(obj, cls, class_name)
  File "/usr/local/lib/python3.10/site-packages/jsonpickle/unpickler.py", line 744, in _restore_object_instance
    instance = self._restore_object_instance_variables(obj, instance)
  File "/usr/local/lib/python3.10/site-packages/jsonpickle/unpickler.py", line 678, in _restore_object_instance_variables
    instance = self._restore_from_dict(obj, instance)
  File "/usr/local/lib/python3.10/site-packages/jsonpickle/unpickler.py", line 605, in _restore_from_dict
    value = self._restore(v)
  File "/usr/local/lib/python3.10/site-packages/jsonpickle/unpickler.py", line 344, in _restore
    return restore(obj)
  File "/usr/local/lib/python3.10/site-packages/jsonpickle/unpickler.py", line 768, in _restore_object
    return self._restore_object_instance(obj, cls, class_name)
  File "/usr/local/lib/python3.10/site-packages/jsonpickle/unpickler.py", line 744, in _restore_object_instance
    instance = self._restore_object_instance_variables(obj, instance)
  File "/usr/local/lib/python3.10/site-packages/jsonpickle/unpickler.py", line 678, in _restore_object_instance_variables
    instance = self._restore_from_dict(obj, instance)
  File "/usr/local/lib/python3.10/site-packages/jsonpickle/unpickler.py", line 621, in _restore_from_dict
    setattr(instance, k, value)
AttributeError: 'Int64' object attribute '_type_marker' is read-only
```
**Json:**
```
{
  "py/object": "dueutil.game.players.Player",
  "py/state": {
    "level": 26,
    "attack": 4230.345344238812,
    "strg": 1793.0706230441306,
    "hp": 260,
    "exp": 31205.69324296505,
    "money": 71552.0,
    "total_exp": 803449.6932429603,
    "accy": 3751.5945070472353,
    "last_progress": 1670508854.5519903,
    "last_quest": 1669079311.3372207,
    "wagers_won": 0,
    "quests_won": 545,
    "quest_day_start": 0,
    "benfont": false,
    "quests_completed_today": 0,
    "quests": [
      {
        "py/object": "dueutil.game.quests.ActiveQuest",
        "py/state": {
          "level": 30,
          "attack": 63896.77511449316,
          "strg": 2056.7263114411303,
          "hp": 777.8485721776085,
          "equipped": {
            "weapon": "0+4915|250|0.86/thisleblade"
          },
          "q_id": "0/gigachad",
          "quester_id": 0,
          "cash_iv": 4.654380986313942,
          "accy": 47521.24435303654,
          "exp": 18364.761340975423,
          "total_exp": 1316229.240367681,
          "money": 1382,
          "name": "gigachad"
        }
      },
      {
        "py/object": "dueutil.game.quests.ActiveQuest",
        "py/state": {
          "level": 31,
          "attack": 4204.402107108459,
          "strg": 4739.319240409045,
          "hp": 517.9891973700958,
          "equipped": { "weapon": "STOCK+66|10|0.28/dagger" },
          "q_id": "0/spambot",
          "quester_id": 0,
          "cash_iv": 4.1092157197032595,
          "accy": 2583.5850541396017,
          "exp": 25694.085994167348,
          "total_exp": 1531093.3441867686,
          "money": 1,
          "name": "spambot"
        }
      },
      {
        "py/object": "dueutil.game.quests.ActiveQuest",
        "py/state": {
          "level": 27,
          "attack": 11853.320954984785,
          "strg": 6304.322635800907,
          "hp": 575.8940041176945,
          "equipped": {
            "weapon": "0+14858|1000|0.65/greatsword of artorias"
          },
          "q_id": "0/sif, the great wolf",
          "quester_id": 0,
          "cash_iv": 7.2616079285232775,
          "accy": 7893.747580068821,
          "exp": 37023.16574506069,
          "total_exp": 1048455.87178918,
          "money": 2376,
          "name": "Sif, The Great Wolf"
        }
      },
      {
        "py/object": "dueutil.game.quests.ActiveQuest",
        "py/state": {
          "level": 29,
          "attack": 3088.5292087911366,
          "strg": 5083.790726995316,
          "hp": 417.8236683823471,
          "equipped": { "weapon": "STOCK+66|10|0.28/dagger" },
          "q_id": "0/mega mouse",
          "quester_id": 0,
          "cash_iv": 3.217933262939009,
          "accy": 2373.1366866368908,
          "exp": 36039.301373856484,
          "total_exp": 1277707.3458005683,
          "money": 1,
          "name": "Mega Mouse"
        }
      },
      {
        "py/object": "dueutil.game.quests.ActiveQuest",
        "py/state": {
          "level": 31,
          "attack": 5668.533297681989,
          "strg": 3696.7587881634854,
          "hp": 502.12326426156767,
          "equipped": { "weapon": "STOCK/none" },
          "q_id": "0/slime",
          "quester_id": 0,
          "cash_iv": 3.5198841870331594,
          "accy": 4154.880232706869,
          "exp": 24735.33840970717,
          "total_exp": 1460535.198638125,
          "money": 1,
          "name": "Slime"
        }
      },
      {
        "py/object": "dueutil.game.quests.ActiveQuest",
        "py/state": {
          "level": 31,
          "attack": 5549.611451859554,
          "strg": 3752.2287670002847,
          "hp": 505.8277797722275,
          "equipped": { "weapon": "STOCK/none" },
          "q_id": "0/slime",
          "quester_id": 0,
          "cash_iv": 4.854819126135674,
          "accy": 4188.6125013878645,
          "exp": 35539.62797404223,
          "total_exp": 1456140.0918140349,
          "money": 1,
          "name": "Slime"
        }
      },
      {
        "py/object": "dueutil.game.quests.ActiveQuest",
        "py/state": {
          "level": 28,
          "attack": 51360.17514258107,
          "strg": 1711.8000226398378,
          "hp": 652.0287563758753,
          "equipped": {
            "weapon": "0+4915|250|0.86/thisleblade"
          },
          "q_id": "0/gigachad",
          "quester_id": 0,
          "cash_iv": 3.5522728644813553,
          "accy": 38305.77525416601,
          "exp": 22652.086257463816,
          "total_exp": 1065175.9248657885,
          "money": 972,
          "name": "gigachad"
        }
      },
      {
        "py/object": "dueutil.game.quests.ActiveQuest",
        "py/state": {
          "level": 30,
          "attack": 15832.091050405099,
          "strg": 15800.014486115773,
          "hp": 615.7419642050178,
          "equipped": { "weapon": "STOCK+16|1|0.66/none" },
          "q_id": "0/marble imp",
          "quester_id": 0,
          "cash_iv": 13.707810495812764,
          "accy": 15667.078116284876,
          "exp": 23646.628309262807,
          "total_exp": 1374021.6979483108,
          "money": 1,
          "name": "Marble Imp"
        }
      },
      {
        "py/object": "dueutil.game.quests.ActiveQuest",
        "py/state": {
          "level": 30,
          "attack": 14191.73357149055,
          "strg": 14770.112207766226,
          "hp": 538.8106410012903,
          "equipped": { "weapon": "STOCK+16|1|0.66/none" },
          "q_id": "0/vegito",
          "quester_id": 0,
          "cash_iv": 17.174099037718843,
          "accy": 14912.32477636199,
          "exp": 21159.544740805235,
          "total_exp": 1309687.5153095669,
          "money": 1,
          "name": "Vegito"
        }
      },
      {
        "py/object": "dueutil.game.quests.ActiveQuest",
        "py/state": {
          "level": 31,
          "attack": 33787.68499181929,
          "strg": 33302.339090937014,
          "hp": 1178.652121381326,
          "equipped": { "weapon": "STOCK+16|1|0.66/none" },
          "q_id": "0/ali a",
          "quester_id": 0,
          "cash_iv": 40.13578050481805,
          "accy": 67740.62407475902,
          "exp": 38519.5468831694,
          "total_exp": 1450473.0535886001,
          "money": 1,
          "name": "Ali A"
        }
      },
      {
        "py/object": "dueutil.game.quests.ActiveQuest",
        "py/state": {
          "level": 27,
          "attack": 2369913.7162904497,
          "strg": 236312.97330800042,
          "hp": 26853.83714979393,
          "equipped": {
            "weapon": "0+1965715|100000|0.86/meth"
          },
          "q_id": "0/jesse pinkman",
          "quester_id": 0,
          "cash_iv": 2.8855524630331977,
          "accy": 1553.0281631324406,
          "exp": 20411.9151082191,
          "total_exp": 971745.6604057654,
          "money": 1276,
          "name": "Jesse Pinkman"
        }
      },
      {
        "py/object": "dueutil.game.quests.ActiveQuest",
        "py/state": {
          "level": 26,
          "attack": 3580.731943660807,
          "strg": 4984.609597380109,
          "hp": 503.8304665106354,
          "equipped": {
            "weapon": "0+4915|250|0.86/thistleblade"
          },
          "q_id": "0/ultiel",
          "quester_id": 0,
          "cash_iv": 7.931985590474895,
          "accy": 3282.462951915823,
          "exp": 22055.980973326266,
          "total_exp": 881794.7019635671,
          "money": 1270,
          "name": "Ultiel"
        }
      },
      {
        "py/object": "dueutil.game.quests.ActiveQuest",
        "py/state": {
          "level": 32,
          "attack": 4439.136078285997,
          "strg": 7561.316833913161,
          "hp": 519.1109956195013,
          "equipped": { "weapon": "STOCK+16|1|0.66/none" },
          "q_id": "0/anonymous",
          "quester_id": 0,
          "cash_iv": 3.487750916707387,
          "accy": 3808.484206301877,
          "exp": 38965.40965172254,
          "total_exp": 1661360.4958937233,
          "money": 1,
          "name": "Anonymous"
        }
      }
    ],
    "received_wagers": [
      {
        "py/object": "dueutil.game.battles.BattleRequest",
        "sender_id": {
          "py/object": "bson.int64.Int64",
          "py/newargs": { "py/tuple": [399454183083868171] },
          "_type_marker": 18,
          "as_integer_ratio": {
            "py/function": "bson.int64.Int64.as_integer_ratio"
          },
          "bit_count": { "py/function": "bson.int64.Int64.bit_count" },
          "bit_length": { "py/function": "bson.int64.Int64.bit_length" },
          "conjugate": { "py/function": "bson.int64.Int64.conjugate" },
          "denominator": 1,
          "from_bytes": { "py/function": "builtins.Int64.from_bytes" },
          "imag": 0,
          "numerator": 399454183083868171,
          "real": 399454183083868171,
          "to_bytes": { "py/function": "bson.int64.Int64.to_bytes" }
        },
        "receiver_id": 0,
        "wager_amount": 2
      },
      {
        "py/object": "dueutil.game.battles.BattleRequest",
        "sender_id": { "py/id": 44 },
        "receiver_id": 0,
        "wager_amount": 1
      },
      {
        "py/object": "dueutil.game.battles.BattleRequest",
        "sender_id": { "py/id": 44 },
        "receiver_id": 0,
        "wager_amount": 25
      }
    ],
    "awards": [
      "RedMist",
      "Potato",
      "Spender",
      "QuestLoser",
      "SugarDaddy",
      "QuestDone",
      "YouLose",
      "Discoin",
      "CritHit",
      "Rank1",
      "Rank2",
      "SoCold"
    ],
    "quest_spawn_build_up": 1,
    "donor": false,
    "misc_stats": {
      "emojis_given": 0,
      "emojis": 0,
      "potatoes": 4,
      "potatoes_given": 13,
      "average_spelling_correctness": 1.0,
      "average_quest_battle_turns": 1.3790542175690284,
      "art_created": 43,
      "quest_losing_streak": 0
    },
    "equipped": {
      "weapon": "0+176915|9000|0.86/mml2 daemonhammer",
      "banner": "old wood",
      "theme": "default",
      "background": "classic doom poster"
    },
    "inventory": {
      "weapons": [
        "0+5|10|0.02/fart tnt",
        "0+85715|5000|0.75/sacred gear"
      ],
      "themes": ["default"],
      "backgrounds": ["default", "classic doom poster"],
      "banners": ["discord blue", "old wood", "teal"]
    },
    "command_rate_limits": {
      "train_saved_cooldown": 1662432785,
      "daily_saved_cooldown": 1664539085,
      "blackjack_saved_cooldown": 1661099743,
      "weekly_saved_cooldown": 1660688866,
      "russianroulette_saved_cooldown": 1619440685
    },
    "team": null,
    "team_invites": [],
    "prestige_level": 0,
    "weapon_hidden": false,
    "gamble_play": false,
    "last_played": 1661099742.1453059,
    "no_save": false,
    "id": 0,
    "name": "juice"
  }
}
```

**Comment by Theelx** [comment]
Sorry, I forgot to comment on this! This appears to come from the Int64 definition here: https://github.com/mongodb/mongo-python-driver/blob/64192663954569fab553c60d3259017a1a7b5fcb/bson/int64.py#L20, and the _type_marker definition seems to be read-only because it's a class attribute of a class that inherits from a type implemented in C (int) that is read-only. I'm going to add something where if an AttributeError is raised, it checks if the parent class inherits from int, and if so it'll skip the error.

**Comment by DeveloperAnonymous** [comment]
Sounds good 👍
