### ISSUE TITLE
Python 3.13 regressions

### ISSUE THREAD

**Issue by musicinmybrain** [jsonpickle/jsonpickle#504]
It’s very hard to test this in a `virtualenv` due to dependencies that are not ready for Python 3.13. However, we’re testing with patched dependencies in Fedora, and Python 3.13 will soon be the system Python in Fedora Rawhide (the development version).

When we [tried to build jsonpickle with Python 3.13.0b1](https://copr.fedorainfracloud.org/coprs/g/python/python3.13/build/7509658/), we encountered the following regressions related to importing modules while unpickling:

```
=================================== FAILURES ===================================
___________________ [doctest] jsonpickle.unpickler.loadrepr ____________________
275 Returns an instance of the object from the object's repr() string.
276 It involves the dynamic specification of code.
277 
278 >>> obj = loadrepr('datetime/datetime.datetime.now()')
UNEXPECTED EXCEPTION: NameError("name 'datetime' is not defined")
Traceback (most recent call last):
  File "/usr/lib64/python3.13/doctest.py", line 1395, in __run
    exec(compile(example.source, filename, "single",
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                 compileflags, True), test.globs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<doctest jsonpickle.unpickler.loadrepr[0]>", line 1, in <module>
  File "/builddir/build/BUILD/python-jsonpickle-3.0.4-build/jsonpickle-3.0.4/jsonpickle/unpickler.py", line 289, in loadrepr
    return eval(evalstr)
  File "<string>", line 1, in <module>
NameError: name 'datetime' is not defined. Did you forget to import 'datetime'?
/builddir/build/BUILD/python-jsonpickle-3.0.4-build/jsonpickle-3.0.4/jsonpickle/unpickler.py:278: UnexpectedException
___________________ PicklingTestCase.test_thing_with_module ____________________

self = <jsonpickle_test.PicklingTestCase testMethod=test_thing_with_module>

    def test_thing_with_module(self):
        obj = Thing('with-module')
        obj.themodule = os
    
        flattened = self.pickler.flatten(obj)
>       inflated = self.unpickler.restore(flattened)

tests/jsonpickle_test.py:392: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
jsonpickle/unpickler.py:378: in restore
    value = self._restore(obj)
jsonpickle/unpickler.py:360: in _restore
    return restore(obj)
jsonpickle/unpickler.py:797: in _restore_object
    return self._restore_object_instance(obj, cls, class_name)
jsonpickle/unpickler.py:772: in _restore_object_instance
    instance = self._restore_object_instance_variables(obj, instance)
jsonpickle/unpickler.py:706: in _restore_object_instance_variables
    instance = self._restore_from_dict(obj, instance)
jsonpickle/unpickler.py:621: in _restore_from_dict
    value = self._restore(v)
jsonpickle/unpickler.py:360: in _restore
    return restore(obj)
jsonpickle/unpickler.py:548: in _restore_repr
    obj = loadrepr(obj[tags.REPR])
jsonpickle/unpickler.py:289: in loadrepr
    return eval(evalstr)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   NameError: name 'os' is not defined. Did you forget to import 'os'?

<string>:1: NameError
__________________ PicklingTestCase.test_thing_with_submodule __________________

self = <jsonpickle_test.PicklingTestCase testMethod=test_thing_with_submodule>

    def test_thing_with_submodule(self):
        obj = Thing('with-submodule')
        obj.submodule = collections
    
        flattened = self.pickler.flatten(obj)
>       inflated = self.unpickler.restore(flattened)

tests/jsonpickle_test.py:408: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
jsonpickle/unpickler.py:378: in restore
    value = self._restore(obj)
jsonpickle/unpickler.py:360: in _restore
    return restore(obj)
jsonpickle/unpickler.py:797: in _restore_object
    return self._restore_object_instance(obj, cls, class_name)
jsonpickle/unpickler.py:772: in _restore_object_instance
    instance = self._restore_object_instance_variables(obj, instance)
jsonpickle/unpickler.py:706: in _restore_object_instance_variables
    instance = self._restore_from_dict(obj, instance)
jsonpickle/unpickler.py:621: in _restore_from_dict
    value = self._restore(v)
jsonpickle/unpickler.py:360: in _restore
    return restore(obj)
jsonpickle/unpickler.py:548: in _restore_repr
    obj = loadrepr(obj[tags.REPR])
jsonpickle/unpickler.py:289: in loadrepr
    return eval(evalstr)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   NameError: name 'collections' is not defined. Did you forget to import 'collections'?

<string>:1: NameError
=============================== warnings summary ===============================
../../../../../usr/lib64/python3.13/site-packages/sqlalchemy/sql/sqltypes.py:1902
  /usr/lib64/python3.13/site-packages/sqlalchemy/sql/sqltypes.py:1902: DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.fromtimestamp(timestamp, datetime.UTC).
    epoch = dt.datetime.utcfromtimestamp(0)

tests/bson_test.py::BSONTestCase::test_FixedOffsetSerializable
  /usr/lib64/python3.13/site-packages/bson/__init__.py:193: DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.fromtimestamp(timestamp, datetime.UTC).
    EPOCH_NAIVE = datetime.datetime.utcfromtimestamp(0)

tests/datetime_test.py: 12 warnings
  /builddir/build/BUILD/python-jsonpickle-3.0.4-build/jsonpickle-3.0.4/tests/datetime_test.py:45: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
    self._dt_read = datetime.datetime.utcnow()

tests/datetime_test.py::DateTimeInnerReferenceTestCase::test_object_with_inner_datetime_refs
tests/datetime_test.py::DateTimeInnerReferenceTestCase::test_object_with_inner_datetime_refs
  /builddir/build/BUILD/python-jsonpickle-3.0.4-build/jsonpickle-3.0.4/tests/datetime_test.py:55: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
    self._dt_read = datetime.datetime.utcnow()

tests/datetime_test.py::DateTimeSimpleTestCase::test_utc
  /builddir/build/BUILD/python-jsonpickle-3.0.4-build/jsonpickle-3.0.4/tests/datetime_test.py:153: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
    self._roundtrip(datetime.datetime.utcnow().replace(tzinfo=utc))

tests/feedparser_test.py::FeedParserTestCase::test
tests/feedparser_test.py::FeedParserTestCase::test
tests/feedparser_test.py::FeedParserTestCase::test
tests/feedparser_test.py::FeedParserTestCase::test
tests/feedparser_test.py::FeedParserTestCase::test
tests/feedparser_test.py::FeedParserTestCase::test
  /usr/lib/python3.13/site-packages/feedparser/html.py:152: DeprecationWarning: 'count' is passed as positional argument
    data = re.sub(r'<!((?!DOCTYPE|--|\[))', r'&lt;!\1', data, re.IGNORECASE)

tests/numpy_test.py::test_ndarray_roundtrip
tests/sklearn_test.py::test_decision_tree
  /builddir/build/BUILD/python-jsonpickle-3.0.4-build/jsonpickle-3.0.4/jsonpickle/ext/numpy.py:305: UserWarning: ndarray is defined by reference to an object we do not know how to serialize. A deep copy is serialized instead, breaking memory aliasing.
    warnings.warn(msg)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED jsonpickle/unpickler.py::jsonpickle.unpickler.loadrepr
FAILED tests/jsonpickle_test.py::PicklingTestCase::test_thing_with_module - N...
FAILED tests/jsonpickle_test.py::PicklingTestCase::test_thing_with_submodule
============ 3 failed, 344 passed, 3 xpassed, 25 warnings in 1.29s =============
```

**Comment by davvid** [comment]
Thanks for the heads-up!

I don't have python3.13 handy for testing, but I think this may have been addressed in https://github.com/jsonpickle/jsonpickle/pull/505

@musicinmybrain do you have an easy way to test that commit from my fork?

```
git remote add davvid http://github.com/davvid/jsonpickle.git
git fetch davvid
git checkout -b eval-py3.13 davvid/eval-py3.13
```

Let me know if that fixes things.

**Comment by musicinmybrain** [comment]
> Let me know if that fixes things.

Yes, I applied https://github.com/jsonpickle/jsonpickle/pull/505/commits/a64e211486f10d928f96f0b08533a48815ae9164.patch to the 3.0.4 release, and all tests passed:

```
============================= test session starts ==============================
platform linux -- Python 3.13.0b1, pytest-7.4.3, pluggy-1.3.0
benchmark: 4.0.0 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /builddir/build/BUILD/python-jsonpickle-3.0.4-build/jsonpickle-3.0.4
configfile: pytest.ini
plugins: benchmark-4.0.0
collected 350 items

jsonpickle/pickler.py ...                                                [  0%]
jsonpickle/unpickler.py .......                                          [  2%]
jsonpickle/util.py .................                                     [  7%]
tests/backend_test.py .............                                      [ 11%]
tests/bson_test.py ......                                                [ 13%]
tests/collections_test.py ......                                         [ 14%]
tests/datetime_test.py .................                                 [ 19%]
tests/document_test.py .                                                 [ 20%]
tests/ecdsa_test.py .                                                    [ 20%]
tests/feedparser_test.py .                                               [ 20%]
tests/handler_test.py ......                                             [ 22%]
tests/jsonpickle_test.py ............................................... [ 35%]
..................................................................       [ 54%]
tests/numpy_test.py .....................                                [ 60%]
tests/object_test.py ..................................................X [ 75%]
XX................                                                       [ 80%]
tests/pandas_test.py ........................                            [ 87%]
tests/sklearn_test.py ..                                                 [ 87%]
tests/sqlalchemy_test.py ...                                             [ 88%]
tests/stdlib_test.py ...                                                 [ 89%]
tests/util_test.py ..................................                    [ 99%]
tests/wizard_test.py ..                                                  [ 99%]
tests/zoneinfo_test.py .                                                 [100%]

=============================== warnings summary ===============================
=============================== warnings summary ===============================
../../../../../usr/lib64/python3.13/site-packages/sqlalchemy/sql/sqltypes.py:1902
  /usr/lib64/python3.13/site-packages/sqlalchemy/sql/sqltypes.py:1902: DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware 
objects to represent datetimes in UTC: datetime.datetime.fromtimestamp(timestamp, datetime.UTC).
    epoch = dt.datetime.utcfromtimestamp(0)

tests/bson_test.py::BSONTestCase::test_FixedOffsetSerializable
  /usr/lib64/python3.13/site-packages/bson/__init__.py:193: DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.fromtimestamp(timestamp, datetime.UTC).
    EPOCH_NAIVE = datetime.datetime.utcfromtimestamp(0)

tests/datetime_test.py: 12 warnings
  /builddir/build/BUILD/python-jsonpickle-3.0.4-build/jsonpickle-3.0.4/tests/datetime_test.py:45: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
    self._dt_read = datetime.datetime.utcnow()

tests/datetime_test.py::DateTimeInnerReferenceTestCase::test_object_with_inner_datetime_refs
tests/datetime_test.py::DateTimeInnerReferenceTestCase::test_object_with_inner_datetime_refs
  /builddir/build/BUILD/python-jsonpickle-3.0.4-build/jsonpickle-3.0.4/tests/datetime_test.py:55: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
    self._dt_read = datetime.datetime.utcnow()

tests/datetime_test.py::DateTimeSimpleTestCase::test_utc
  /builddir/build/BUILD/python-jsonpickle-3.0.4-build/jsonpickle-3.0.4/tests/datetime_test.py:153: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
    self._roundtrip(datetime.datetime.utcnow().replace(tzinfo=utc))

tests/feedparser_test.py::FeedParserTestCase::test
tests/feedparser_test.py::FeedParserTestCase::test
tests/feedparser_test.py::FeedParserTestCase::test
tests/feedparser_test.py::FeedParserTestCase::test
tests/feedparser_test.py::FeedParserTestCase::test
tests/feedparser_test.py::FeedParserTestCase::test
  /usr/lib/python3.13/site-packages/feedparser/html.py:152: DeprecationWarning: 'count' is passed as positional argument
    data = re.sub(r'<!((?!DOCTYPE|--|\[))', r'&lt;!\1', data, re.IGNORECASE)

tests/numpy_test.py::test_ndarray_roundtrip
tests/sklearn_test.py::test_decision_tree
  /builddir/build/BUILD/python-jsonpickle-3.0.4-build/jsonpickle-3.0.4/jsonpickle/ext/numpy.py:305: UserWarning: ndarray is defined by reference to an object we do not know how to serialize. A deep copy is serialized instead, breaking memory aliasing.
    warnings.warn(msg)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
================= 347 passed, 3 xpassed, 25 warnings in 1.07s ==================
```

I could also test a snapshot from your fork if that’s if it’s helpful for some reason, but #505 is clearly a fix for the issues reported here. Thank you!
